### ISSUE TITLE
Crash: label/control index error

### ISSUE THREAD

**Issue by caugolm** [PennLINC/aslprep#126]
Hi, I've submitted a job (IDs redacted for privacy reasons) but I'm finding a crash report in my output. It looks like the indices aren't lining up for my time series, but don't understand why it shouldn't be working.

My time series has 29 volumes: 15 labels, and 14 controls, which are all specified in my aslcontext.tsv. I'm using the option "--dummy_vols 1" to try to drop the leading label volume, so I can have 14 "matched" pairs of labels and controls. Is the issue that my aslcontext file should only contain the "not dropped" volumes? Or, is there another issue I'm missing?

I'm using ASLPREP version "aslprep-0.2.6pasl", with a clean working directory.

Submitted job:
singularity run -e -B ${binddir}:${binddir},${TEMPLATEFLOW_HOME:-$HOME/.cache/templateflow}:/templateflow ${SIMG} ${bidsdir} ${outdir} participant --participant_label ${i} --nprocs 8 -w ${wkdir} --skip_bids_validation  --basil --scorescrub --m0_scale 10 --dummy-vols 1 --sloppy 

Crash report:
Node inputs:

file_type = d
in_asl = /project/ftdc_hcp/aslprep/bids2/sub-NNN/perf/sub-NNN_task-rest_asl.nii.gz
in_aslmask = /project/ftdc_hcp/aslprep/wrkdir/aslprep_wf/single_subject_NNN_wf/asl_preproc_task_rest_wf/asl_gereference_wf/fslbet/aslref_reference_brain_mask.nii.gz
out_file = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/interfaces/cbf_computation.py", line 1369, in _run_interface
    ffdata=fdata[:, :, :, controllist]-fdata[:, :, :, labelist]
IndexError: index 3 is out of bounds for axis 3 with size 2

Thanks for any help!

**Comment by caugolm** [comment]
Update: I re-ran with the aslcontext.tsv containing only 14 labels and 14 controls and got the same error.
Thanks!

**Comment by caugolm** [comment]
I apologize-- my "asl.nii.gz" and "m0scan.nii.gz" were flipped. ...Closing issue
