### ISSUE TITLE
BIDS validator bug

### ISSUE THREAD

**Issue by caugolm** [PennLINC/aslprep#140]
Hi Azeez,
It seems like there's been a lot of progress to get the ASLPREP working with BIDS, which is fantastic! It looks like there might be a bug in the form of a directory path not being passed correctly. The error looks like it comes from the validate_input_dir function in the aslprep/utils/bids.py script. 

Based on the last couple of lines of the job output/crash report:
 
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/utils/bids.py", line 140, in validate_input_dir
    subprocess.check_call(['bids-validator', bids_dir, '-c', temp.name])
  File "/usr/local/miniconda/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bids-validator', PosixPath('/project/ftdc_volumetric/MultiCenter/LEFFTDS/aslprep/bids3'), '-c', '/tmp/tmp3rs8edz3']' returned non-zero exit status 3.

Tracing some variables back, the bids_dir variable is declared a "Path()" but the temp.name variable is not, so adding a line 
   temp.name = Path(temp.name)
might be all that's needed here. 

Thanks so much for your help! 

(here's the full job output, in case I'm overlooking something)

Unhandled rejection (
  reason: TypeError: Cannot read property 'split' of undefined
    at Minimatch.match (/usr/lib/node_modules/bids-validator/node_modules/minimatch/minimatch.js:717:9)
    at minimatch (/usr/lib/node_modules/bids-validator/node_modules/minimatch/minimatch.js:107:42)
    at Object.ignoredFile (/usr/lib/node_modules/bids-validator/utils/config.js:11:13)
    at Function.format (/usr/lib/node_modules/bids-validator/utils/issues/index.js:65:16)
    at Function.exceptionHandler (/usr/lib/node_modules/bids-validator/utils/issues/index.js:191:25)
    at validateMisc.then.then.then.then.then.then.then.then.catch.err (/usr/lib/node_modules/bids-validator/validators/bids/fullTest.js:217:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
).

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/aslprep", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/cli/run.py", line 17, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/cli/parser.py", line 588, in parse_args
    config.environment.exec_env, opts.bids_dir, opts.participant_label
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/utils/bids.py", line 140, in validate_input_dir
    subprocess.check_call(['bids-validator', bids_dir, '-c', temp.name])
  File "/usr/local/miniconda/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bids-validator', PosixPath('/project/ftdc_volumetric/MultiCenter/LEFFTDS/aslprep/bids3'), '-c', '/tmp/tmp3rs8edz3']' returned non-zero exit status 3.

**Comment by a3sha2** [comment]
which bids-validator version are you using?
it requires bids-validator-v1.6.2

**Comment by caugolm** [comment]
Sorry, bids-validator-1.6.2 and aslprep 0.2.7 (built 3/8/21)

**Comment by a3sha2** [comment]
I ran bids-validator on those subjects and the bids is not validated yet 
[error.txt](https://github.com/PennLINC/aslprep/files/6112819/error.txt)

**Comment by caugolm** [comment]
Thanks for checking this out! 
I guess I misunderstood the purpose of the BIDS check step in ASLPREP. I take it it's more intended as a "double check" than replacing running the BIDS validator beforehand?
