### ISSUE TITLE
Cbfcomputation error

### ISSUE THREAD

**Issue by ChristianNSchmitz** [PennLINC/aslprep#141]
Dear aslprep-team,

we want to use aslprep in order to analyse our PCASL data. We are running aslprep over docker on Linux.
Unfortunatly, we get an error of the cbf_computation node and would like to ask you for your support. You can see the crash-report here:

```Node: aslprep_wf.single_subject_007_wf.asl_preproc_ses_03_run_02_wf.compt_cbf_wf.computecbf
Working directory: /out/work/aslprep_wf/single_subject_007_wf/asl_preproc_ses_03_run_02_wf/compt_cbf_wf/computecbf

Node inputs:

in_cbf = /out/work/aslprep_wf/single_subject_007_wf/asl_preproc_ses_03_run_02_wf/compt_cbf_wf/extractcbf/sub-007_ses-03_run-02_asl_cbftimeseries.nii.gz
in_m0file = /out/work/aslprep_wf/single_subject_007_wf/asl_preproc_ses_03_run_02_wf/compt_cbf_wf/extractcbf/sub-007_ses-03_run-02_asl_m0file.nii.gz
in_m0scale = 1.0
in_mask = /out/work/aslprep_wf/single_subject_007_wf/asl_preproc_ses_03_run_02_wf/compt_cbf_wf/refinemask/ref_bold_corrected_brain_mask_maths_refinemask.nii.gz
in_metadata = {'AcquisitionVoxelSize': [2.5, 2.5, 3], 'ArterialSpinLabelingType': 'PCASL', 'BackgroundSuppression': True, 'EchoTime': 0.04546, 'LabelingDistance': 90, 'LabelingDuration': 0.7, 'LabelingLocationDescription': 'transversalOnAntComm', 'LabelingPulseAverageGradient': 6, 'LabelingPulseInterval': 0.36, 'M0Type': 'Included', 'MRAcquisitionType': '3D', 'MagneticFieldStrength': 3, 'PostLabelingDelay': [0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1, 1, 1, 1, 1, 1, 1, 1, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 2, 2, 2, 2, 2, 2, 2, 2, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5], 'RepetitionTime': 4.22, 'RepetitionTimePreparation': 2, 'TotalAcquiredPairs': 20, 'VascularCrushing': True}
out_att = <undefined>
out_cbf = <undefined>
out_mean = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/interfaces/cbf_computation.py", line 216, in _run_interface
    cbffile=self.inputs.in_cbf)
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/interfaces/cbf_computation.py", line 320, in cbfcomputation
    cbf_data_ts[:, i] =np.multiply(cbf1[:, i],permfactor[i])
IndexError: index 0 is out of bounds for axis 0 with size 0
```

Thanks for your support!
Christian

**Comment by a3sha2** [comment]
Hi Christian, 

Please is the data validated by bids?

I also noticed that post labelling delay is repeated for like 8 times 

'PostLabelingDelay': [0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1, 1, 1, 1, 1, 1, 1, 1, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 2, 2, 2, 2, 2, 2, 2, 2, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]`

this can just be like this: 
'PostLabelingDelay': [0, 0.5, 1, 1.5, 2, 2.5]

**Comment by ChristianNSchmitz** [comment]
Hey a3sha2,
thanks for your response! Yes, the dataset is validated by bids validator v 1.6.2 and now 1.7.1.

Thanks for the recomendation, I will change that!

**Comment by ChristianNSchmitz** [comment]
Btw: the bids validator didn't accept:  `` 'PostLabelingDelay': [0, 0.5, 1, 1.5, 2, 2.5] ``

**Comment by a3sha2** [comment]
what is the error, pls.

**Comment by ChristianNSchmitz** [comment]
It seems to be not accepted by the bids-validator (the bids validator does accept the other layout of the post labeling delays):
![image](https://user-images.githubusercontent.com/35763466/119689766-6a492280-be49-11eb-9245-efad07a9525f.png)

Have you had a change to take a look at the cbf-error?
Thanks!

**Comment by geowk** [comment]
I'm having a similar error.  Our dataset is bids validated and passes.

Something also strange is that our original metadata designates Vascular crushing and Background suppression as false, however that seems to have been changed to true during aslprep processing for some reason. See the below output.

Any insights would greatly be appreciated.


```
Node: aslprep_wf.single_subject_1050_wf.asl_preproc_ses_01_acq_REST_run_04_wf.compt_cbf_wf.extractcbf
Working directory: /work/aslprep_wf/single_subject_1050_wf/asl_preproc_ses_01_acq_REST_run_04_wf/compt_cbf_wf/extractcbf

Node inputs:

asl_file = /work/aslprep_wf/single_subject_1050_wf/asl_preproc_ses_01_acq_REST_run_04_wf/asl_asl_trans_wf/merge/vol0000_xform-00000_merged.nii
bids_dir = /data/sub-1050
dummy_vols = 0
fwhm = 5.0
in_file = /data/sub-1050/ses-01/perf/sub-1050_ses-01_acq-REST_run-04_asl.nii
in_mask = /work/aslprep_wf/single_subject_1050_wf/asl_preproc_ses_01_acq_REST_run_04_wf/compt_cbf_wf/refinemask/ref_bold_corrected_brain_mask_maths_refinemask.nii.gz
in_metadata = {'AcquisitionMatrixPE': 76, 'AcquisitionNumber': 1, 'AcquisitionTime': '15:06:40.927500', 'AcquisitionVoxelSize': [3.026316, 3.026316, 6.0], 'ArterialSpinLabelingType': 'PCASL', 'BackgroundSuppression': True, 'BandwidthPerPixelPhaseEncode': 53.706, 'BaseResolution': 76, 'BodyPartExamined': 'BRAIN', 'ConsistencyInfo': 'N4_VE11C_LATEST_20160120', 'ConversionSoftware': 'dcm2niix', 'ConversionSoftwareVersion': 'v1.0.20200331', 'DerivedVendorReportedEchoSpacing': 0.000489997, 'DeviceSerialNumber': '167023', 'DwellTime': 2.5e-06, 'EchoTime': 0.013, 'EchoTrainLength': 37, 'EffectiveEchoSpacing': 0.000244999, 'FlipAngle': 90, 'ImageOrientationPatientDICOM': [0.998484, 0.0369896, 0.0407618, -0.0278902, 0.978428, -0.204696], 'ImageType': ['ORIGINAL', 'PRIMARY', 'M', 'ND', 'NORM', 'MOSAIC'], 'ImagingFrequency': 123.239, 'InPlanePhaseEncodingDirectionDICOM': 'COL', 'LabelOffset': 90, 'LabelingDuration': 1.8, 'M0Type': 'Absent', 'MRAcquisitionType': '2D', 'MagneticFieldStrength': 3, 'ManufacturersModelName': 'Prisma_fit', 'MeanGzx10': 6, 'Modality': 'MR', 'NumRFBlocks': 98, 'ParallelReductionFactorInPlane': 2, 'PartialFourier': 1, 'PatientPosition': 'HFS', 'PercentPhaseFOV': 100, 'PercentSampling': 100, 'PhaseEncodingDirection': 'j-', 'PhaseEncodingSteps': 75, 'PhaseResolution': 1, 'PhiAdjust': 100, 'PixelBandwidth': 2630, 'PostLabelDelay': 1.2, 'PostLabelingDelay': 1.2, 'ProtocolName': 'ep2d_pcasl_REST4', 'PulseSequenceDetails': '%CustomerSeq%_ep2d_pcasl_ve11c', 'RFGap': 0.00036, 'ReceiveCoilActiveElements': 'HC1-7', 'ReceiveCoilName': 'HeadNeck_64', 'ReconMatrixPE': 76, 'RefLinesPE': 24, 'RepetitionTime': 4, 'RepetitionTimePreparation': 4.0, 'SAR': 0.285131, 'ScanOptions': 'FS', 'ScanningSequence': 'EP', 'SequenceName': 'epfid2d1_76', 'SequenceVariant': 'SK', 'SeriesDescription': 'ep2d_pcasl_REST4', 'SeriesNumber': 11, 'ShimSetting': [3216, -11938, 6772, 384, -68, -128, -52, -60], 'SliceThickness': 5, 'SliceTiming': [0.3725, 0, 0.41, 0.0375, 0.4475, 0.075, 0.485, 0.1125, 0.5225, 0.15, 0.56, 0.1875, 0.595, 0.225, 0.6325, 0.26, 0.67, 0.2975, 0.7075, 0.335],  'SpacingBetweenSlices': 6, 'StationName': 'MRC35035', 'TotalReadoutTime': 0.0183749, 'TxRefAmp': 239.057, 'VascularCrushing': True}
out_avg = <undefined>
out_file = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/interfaces/cbf_computation.py", line 96, in _run_interface
    idasl = pd.read_csv(aslcontext1)['volume_type'].tolist()
  File "/usr/local/miniconda/lib/python3.7/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/miniconda/lib/python3.7/site-packages/pandas/io/parsers.py", line 446, in _read
    data = parser.read(nrows)
  File "/usr/local/miniconda/lib/python3.7/site-packages/pandas/io/parsers.py", line 1036, in read
    ret = self._engine.read(nrows)
  File "/usr/local/miniconda/lib/python3.7/site-packages/pandas/io/parsers.py", line 1848, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 876, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 891, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 945, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 932, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2112, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 29, saw 3
```

**Comment by conan-chen94** [comment]
geowk, I had run into the same exact error traceback you had. For me it related to the aslcontext.tsv file.

```
# Error in ASLprep
File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/interfaces/cbf_computation.py", line 96, in _run_interface
    idasl = pd.read_csv(aslcontext1)['volume_type'].tolist()

# Lines 96 and 97 of aslprep/interfaces/cbf_computation.py
aslcontext1 = file1.replace('_asl.nii.gz', '_aslcontext.tsv')
idasl = pd.read_csv(aslcontext1)['volume_type'].tolist()
```


My perfusion file was .nii, not .nii.gz, so the aslcontext1 couldn't make the replacement in line 96 and went ahead with the wrong _aslcontext.tsv name, leading to those pandas parsing errors. Just converting to .nii.gz did the trick!

Also, I similarly have the issue of VascularCrushing and BackgroundSuppression going from False to True. It didn't seem to affect processing though.

**Comment by tsalo** [comment]
I've switched to using BIDSLayout to grab aslcontext and m0scan files, so the file selection problem should be resolved.

I don't know how the metadata in the original file would be modified by ASLPrep though. If this is still a problem in 0.3.0, please reopen this issue or open a new one.
