### ISSUE TITLE
Error in sdc workflow (ds_report_sdc - could not build path with entities)

### ISSUE THREAD

**Issue by felenae** [PennLINC/aslprep#174]
Dear developer team,

I am currently trying to set up aslprep for processing a single delay PCASL 3D GRASE ASL acquisition using singularity on a Centos 7 HPC. In this study we did not acquire fieldmaps, which is why I would like to use the SyN-SDC option of aslprep. However, I am running into the following error (see also attached crash report):

```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/bids.py", line 565, in _run_interface
    raise ValueError(f"Could not build path with entities {out_entities}.")
ValueError: Could not build path with entities {'subject': '<>', 'session': '1', 'suffix': 'bold', 'extension': 'svg', 'datatype': 'figures', 'desc': 'sdc'}.
```
##### operating system
Centos 7

##### singularity version
3.5.2

##### aslprep version
0.2.7

#### aslprep command call
```
 singularity run --cleanenv --userns \
    -B $PROJ_DIR \
    -B $(readlink -f $ENV_DIR) \
    -B $TMP_DIR/:/tmp \
    -B $TMP_IN:/tmp_in \
    -B $TMP_OUT:/tmp_out \
    $ENV_DIR/$container_aslprep \
       /tmp_in /tmp_out participant \
       --participant-label $1 \
       --work-dir /tmp \
       --fs-license-file envs/freesurfer_license.txt \
       --skip-bids-validation \
       --nthreads $SLURM_CPUS_PER_TASK \
       --omp-nthreads $OMP_NTHREADS \
       --mem_mb $MEM_MB \
       --ignore fieldmaps slicetiming sbref \
       --output-spaces asl T1w MNI152NLin2009cAsym \
       --asl2t1w-init register \
       --asl2t1w-dof 6 \
       --force-bbr
       --use-syn-sdc
       --force-syn
       --m0_scale 10 \
       --scorescrub \
       --basil \
       --skull-strip-template OASIS30ANTs \
       --skull-strip-fixed-seed \
       --random-seed 42 \
       --skull-strip-t1w force \
       --notrack \
       --stop-on-first-crash
```
##### Of note: When running alsprep without --use-syn-sdc / --force-syn, the pipeline finishes as expected. 

Do you see an obvious usage mistake or do you have an idea how to fix this problem?

I would greatly appreciate your help!

Thanks in advance,
Felix

[crash_report.txt](https://github.com/PennLINC/aslprep/files/7648953/crash_report.txt)

**Comment by a3sha2** [comment]
Hello Felix,
distortion correction works, but this error is from report generation.  we will correct it

**Comment by felenae** [comment]
Hi Azeez,
thanks for your quick reply. In fact, when omitting the --stop-on-first-crash flag the pipeline finishes with the desired output.
Best, Felix
