### ISSUE TITLE
Error in scorescrub workflow and missing outputs in template / MNI space

### ISSUE THREAD

**Issue by felenae** [PennLINC/aslprep#176]
Dear Azeez,

I would like to consult you concerning another issue I am facing for a few subjects when running aslprep-2.0.7 on 3D PCASL data using singularity on a Centos 7 HPC:

#### Error
```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/interfaces/cbf_computation.py", line 408, in _run_interface
    mask=mask, wfun=self.inputs.in_wfun, thresh=self.inputs.in_thresh)
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/interfaces/cbf_computation.py", line 672, in _scrubcbf
    + (mu1 >= 10*thresh1)*(1/(2*thresh1*10) * np.power(mu1, 2))+(thresh1*10/2 - thresh1)
ZeroDivisionError: float division by zero
```
Furthermore, in subjects for which this error occurs, asl output in template space (MNI152NLin2009cAsym) is missing.

#### aslprep call
```
singularity run --cleanenv --userns \
    -B $PROJ_DIR \
    -B $(readlink -f $ENV_DIR) \
    -B $TMP_DIR/:/tmp \
    -B $TMP_IN:/tmp_in \
    -B $TMP_OUT:/tmp_out \
    $ENV_DIR/$container_aslprep \
         /tmp_in /tmp_out participant \
         --participant-label $1 \
         --work-dir /tmp \
         --fs-license-file envs/freesurfer_license.txt \
         --skip-bids-validation \
         --nthreads $SLURM_CPUS_PER_TASK \
         --omp-nthreads $OMP_NTHREADS \
         --mem_mb $MEM_MB \
         --ignore fieldmaps slicetiming sbref \
         --output-spaces asl T1w MNI152NLin2009cAsym \
         --asl2t1w-init register \
         --asl2t1w-dof 6 \
         --force-bbr
         --use-syn-sdc
         --force-syn
         --m0_scale 10 \
         --scorescrub \
         --basil \
         --skull-strip-template OASIS30ANTs \
         --skull-strip-fixed-seed \
         --random-seed 42 \
         --skull-strip-t1w force \
         --notrack \
         --verbose"
```
**Of note**: There are no obvious flaws of the raw input data (T1w, asl, m0scan) and, surprisingly, the readout of atlas ROIs is available as output, for which I assume transformation to template space is a prerequisite.

Do you think the error is linked to the missing output in template space? And do you have any thoughts on how to address the error?

Your help is greatly appreciated!
Thanks and all the best,
Felix

[scorescrub_error.txt](https://github.com/PennLINC/aslprep/files/7705504/scorescrub_error.txt)

**Comment by a3sha2** [comment]
this may due to the data, likely labe-control issues. this mostly occur when the cbf have more  zero or negative values

**Comment by tsalo** [comment]
@felenae did you ever figure out what the problem was/find a solution?
