### ISSUE TITLE
Path error

### ISSUE THREAD

**Issue by Jian-uon** [PennLINC/aslprep#281]
## Summary
Preprocessing failed.

## Additional details
- ASLPrep version:unstable
- Docker version: 23.0.5, build bc4487a, MAC OS
- Singularity version:

## Reproducing the bug
My command:

```
docker run -v /Users/jianhu/Documents/OSIPI/Dataset6:/data  -v /Users/jianhu/Documents/license.txt:/license.txt pennlinc/aslprep /data/rawdata /data/results participant --participant-label 101 -w /work --fs-license-file /license.txt 

```

```
Node: aslprep_wf.single_subject_101_wf.asl_preproc_run_1_wf.parcellate_cbf_wf.warp_atlases_to_asl_space
Working directory: /work/aslprep_wf/single_subject_101_wf/asl_preproc_run_1_wf/parcellate_cbf_wf/warp_atlases_to_asl_space

Node inputs:

args = <undefined>
default_value = 0.0
dimension = 3
environ = {'NSLOTS': '1'}
float = False
input_image = <undefined>
input_image_type = 3
interpolation = GenericLabel
interpolation_parameters = <undefined>
invert_transform_flags = <undefined>
num_threads = 1
out_postfix = _trans
output_image = <undefined>
print_out_composite_warp_file = <undefined>
reference_image = <undefined>
transforms = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 292, in _send_procs_to_workers
    num_subnodes = self.procs[jobid].num_subnodes()
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 1308, in num_subnodes
    self._get_inputs()
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 1322, in _get_inputs
    super(MapNode, self)._get_inputs()
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 619, in _get_inputs
    self.set_input(key, deepcopy(output_value))
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 1157, in set_input
    self._set_mapnode_input(parameter, deepcopy(val))
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 1164, in _set_mapnode_input
    setattr(self._inputs, name, newvalue)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 424, in validate
    value = super(MultiObject, self).validate(objekt, name, newvalue)
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/trait_types.py", line 2699, in validate
    return TraitListObject(self, object, name, value)
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/trait_list_object.py", line 582, in __init__
    super().__init__(
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/trait_list_object.py", line 213, in __init__
    super().__init__(self.item_validator(item) for item in iterable)
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/trait_list_object.py", line 213, in <genexpr>
    super().__init__(self.item_validator(item) for item in iterable)
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/trait_list_object.py", line 865, in _item_validator
    return trait_validator(object, self.name, value)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: Each element of the 'input_image' trait of a DynamicTraitedSpec instance must be a pathlike object or string representing an existing file, but a value of '/usr/local/miniconda/lib/python3.8/site-packages/aslprep/data/niftiatlas/Schaefer2018_100Parcels_17Networks_order_FSLMNI152_2mm.nii' <class 'str'> was specified.

Error setting node input:
Node: warp_atlases_to_asl_space
input: input_image
results_file: /work/aslprep_wf/single_subject_101_wf/asl_preproc_run_1_wf/parcellate_cbf_wf/atlas_file_grabber/result_atlas_file_grabber.pklz
value: ['/usr/local/miniconda/lib/python3.8/site-packages/aslprep/data/niftiatlas/Schaefer2018_100Parcels_17Networks_order_FSLMNI152_2mm.nii', '/usr/local/miniconda/lib/python3.8/site-packages/aslprep/data/niftiatlas/Schaefer2018_200Parcels_17Networks_order_FSLMNI152_2mm.nii', '/usr/local/miniconda/lib/python3.8/site-packages/aslprep/data/niftiatlas/Schaefer2018_300Parcels_17Networks_order_FSLMNI152_2mm.nii', '/usr/local/miniconda/lib/python3.8/site-packages/aslprep/data/niftiatlas/Schaefer2018_400Parcels_17Networks_order_FSLMNI152_2mm.nii', '/usr/local/miniconda/lib/python3.8/site-packages/aslprep/data/niftiatlas/Schaefer2018_500Parcels_17Networks_order_FSLMNI152_2mm.nii', '/usr/local/miniconda/lib/python3.8/site-packages/aslprep/data/niftiatlas/Schaefer2018_600Parcels_17Networks_order_FSLMNI152_2mm.nii', '/usr/local/miniconda/lib/python3.8/site-packages/aslprep/data/niftiatlas/Schaefer2018_700Parcels_17Networks_order_FSLMNI152_2mm.nii', '/usr/local/miniconda/lib/python3.8/site-packages/aslprep/data/niftiatlas/Schaefer2018_800Parcels_17Networks_order_FSLMNI152_2mm.nii', '/usr/local/miniconda/lib/python3.8/site-packages/aslprep/data/niftiatlas/Schaefer2018_900Parcels_17Networks_order_FSLMNI152_2mm.nii', '/usr/local/miniconda/lib/python3.8/site-packages/aslprep/data/niftiatlas/Schaefer2018_1000Parcels_17Networks_order_FSLMNI152_2mm.nii', '/usr/local/miniconda/lib/python3.8/site-packages/aslprep/data/niftiatlas/glasser360/glasser360MNI.nii.gz', '/usr/local/miniconda/lib/python3.8/site-packages/aslprep/data/niftiatlas/gordon333/gordon333MNI.nii.gz', '/usr/local/miniconda/lib/python3.8/site-packages/aslprep/data/niftiatlas/TianSubcortical/Tian_Subcortex_S3_3T.nii.gz']


When creating this crashfile, the results file corresponding
to the node could not be found.
```

-->

**Comment by tsalo** [comment]
Thanks for catching this. I forgot to update the package data when I changes the atlases recently. I've opened #282 to address this.

**Comment by tsalo** [comment]
@Jian-uon the fix finally pushed to DockerHub. Would you mind pulling the most recent version of `pennlinc/aslprep:unstable` and testing on that?

**Comment by Jian-uon** [comment]
Sure thing! Thank you!

**Comment by Jian-uon** [comment]
It works well now! Many thanks for your help!
