### ISSUE TITLE
Failing to find bold_series?

### ISSUE THREAD

**Issue by willtack** [PennLINC/aslprep#56]
Hi, I'm using v0.0.4_0.2.3 on Flywheel and received the following error. The analyses that generated this error are under the detre_group/aslprep_testing project I shared with you on Flywheel (any subject). 

```
200831-23:06:51,343 nipype.workflow INFO:
	 [Node] Finished "_t1w_conform0".
200831-23:06:51,349 nipype.workflow INFO:
	 [Node] Finished "aslprep_wf.single_subject_P077_wf.anat_preproc_wf.anat_template_wf.t1w_conform".
200831-23:06:51,356 nipype.workflow CRITICAL:
	 ASLPrep failed: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/interfaces/reports.py", line 101, in _run_interface
    return super(SubjectSummary, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/interfaces/reports.py", line 65, in _run_interface
    segment = self._generate_segment()
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/interfaces/reports.py", line 134, in _generate_segment
    for series in bold_series)
  File "/usr/local/miniconda/lib/python3.7/collections/__init__.py", line 568, in __init__
    self.update(*args, **kwds)
  File "/usr/local/miniconda/lib/python3.7/collections/__init__.py", line 655, in update
    _count_elements(self, iterable)
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/interfaces/reports.py", line 134, in <genexpr>
    for series in bold_series)
TypeError: 'NoneType' object is not subscriptable
```

It looks like it's trying to find a BOLD image. The dataset I'm working with doesn't have any BOLD runs...is that an issue?
I also noticed this sentence [in the docs](https://aslprep.readthedocs.io/en/latest/usage.html), under the ```--output-spaces``` flag: 

> To generate no BOLD outputs, use this option without specifying any spatial references. 

I left ```--output-spaces``` blank to try to circumvent the BOLD workflow, but saw the same result as above. Please advise.

Thanks!

**Comment by a3sha2** [comment]
@willtack  if you left output space blank, the output space will be in MNI space. 
if  you are using flywheel, can you use `--force-bbr `. I am going to upload new one soon 

Your bids is not completed yet. Remember asl required aslcontext, check this https://fw-heudiconv.readthedocs.io/en/latest/tips.html#arterial-spin-labelling-data  on how to do it on flywheel with fw-heudiconv 

we can bluejean/zoom with Chris and @mflounders  to make it easier

**Comment by willtack** [comment]
Will `--force-bbr` fix the above issue and, if so, how?

I do have aslcontext.tsv attached to the session. Should it be attached somewhere else?


<img width="760" alt="aslcontext" src="https://user-images.githubusercontent.com/48965778/91884517-2b889200-ec54-11ea-8912-f7560f0faeef.png">

**Comment by a3sha2** [comment]
<img width="566" alt="Screen Shot 2020-09-03 at 10 50 38 AM" src="https://user-images.githubusercontent.com/8614410/92131046-7da3f180-edd3-11ea-8f55-cfd974b8e0b5.png">

@willtack

**Comment by willtack** [comment]
Yes, I [tried](https://upenn.flywheel.io/#/projects/5f4d203f5ff0e73710a1b69d/sessions/5f4d6e559af1cb9265086622?tab=data) that and got the same error.
