### ISSUE TITLE
deltam and m0 crash

### ISSUE THREAD

**Issue by caugolm** [PennLINC/aslprep#79]
I'm trying to use ASLPREP to get CBF maps from data where the raw images are a difference image and an m0. My "bidsification" calls the difference image "_asl.nii.gz" and the m0 the "_m0scan.nii.gz", with the _aslcontext.tsv having one line: "deltam" (I also tried calling the difference image "_deltam.nii.gz" produced an error saying that an ASL image is required for ASLPREP).

However, I'm getting a crash log error:
Node inputs:

in_file = <undefined>
mc_method = AFNI
multiecho = False
sbref_file = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/niworkflows/interfaces/registration.py", line 496, in _run_interface
    n_volumes_to_discard = _get_vols_to_discard(ref_im)
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/niworkflows/interfaces/registration.py", line 552, in _get_vols_to_discard
    data_slice = img.dataobj[:, :, :, :50]
IndexError: too many indices for array

Because it's an array indices error I'm wondering if it's expecting my ASL image to be 4D. Do you have any recommendation for what I can do? Thanks!

**Comment by a3sha2** [comment]
@caugolm 

ASLPrep  is expecting asl file to be 4D, it can be `deltam` or `label` and `control`. Also `m0scan` can be included in the aslcontext.tsv as well as described in ASL BIDS. It wont work with one volume of ASL file, because of reference generation.

**Comment by caugolm** [comment]
Thanks! I'll merge the deltam and M0 into the asl.nii.gz and give it another go.

**Comment by caugolm** [comment]
Unfortunately, I've ended up with another error.

The changes I made to my BIDS files:  
Merged the m0scan and deltam into a single 4D image ("_asl.nii.gz") 
My aslcontext.tsv changed to:
    m0scan 
    deltam
I changed the M0 field of my asl.json to 
    "M0:" true

The error (from standard error file) is as follows:
 
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/cli/workflow.py", line 84, in build_workflow
    retval["workflow"] = init_aslprep_wf()
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/workflows/base.py", line 64, in init_aslprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/workflows/base.py", line 307, in init_single_subject_wf
    ('outputnode.fsnative2t1w_xfm', 'inputnode.fsnative2t1w_xfm')]),
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 158, in connect
    self._check_nodes(newnodes)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 766, in _check_nodes
    raise IOError('Duplicate node name "%s" found.' % node.name)
OSError: Duplicate node name "asl_preproc_ses_123456_task_rest_wf" found.

**Comment by caugolm** [comment]
This error turned out to be due to re-running a failed session without removing the working directory.
However, now I've run into a different problem-- with the deltam and m0scan in the same volume, the asl.json needs the M0 key to be true. Without quotes, it gives me an error saying that a boolean isn't accepted. 
So I changed it to 
"M0:" "true" 
but then it thinks that "true" is the name of the m0scan so I get the following error: 

File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/interfaces/cbf_computation.py", line 108, in _run_interface
    m0file_metadata=readjson(m0file.replace('nii.gz','json'))
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/interfaces/cbf_computation.py", line 1137, in readjson
    with open(jsonfile) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/project/ftdc_volumetric/MultiCenter/LEFFTDS/aslprep/bidsout/sub-1001767/true'

Thanks for any help!

**Comment by a3sha2** [comment]
@caugolm 
pls can you share sample of the data you are suing with me

**Comment by caugolm** [comment]
Thanks! Email sent

**Comment by tsalo** [comment]
Does anyone know if this was resolved?
